### ISSUE TITLE
Found dead link ./index in file /home/runner/work/doc-vite/doc-vite/docs/deepin-src-col/sec-2.md

### ISSUE THREAD

**Issue by pzm9012** [pzm9012/doc-vite#1]
Github Actions 的输出结果：
```
Found dead link ./index in file /home/runner/work/doc-vite/doc-vite/docs/deepin-src-col/sec-2.md
If it is intended, you can use:
    <a href="./index" target="_blank" rel="noreferrer">./index</a>
[vitepress] One or more pages contain dead links.
✖ building client + server bundles...
build error:
Error: One or more pages contain dead links.
    at Object.renderStart (file:///home/runner/work/doc-vite/doc-vite/node_modules/vitepress/dist/node/serve-a6868a38.js:36802:15)
    at file:///home/runner/work/doc-vite/doc-vite/node_modules/rollup/dist/es/shared/node-entry.js:24343:40
    at async Promise.all (index 0)
    at async PluginDriver.hookParallel (file:///home/runner/work/doc-vite/doc-vite/node_modules/rollup/dist/es/shared/node-entry.js:24271:9)
    at async Bundle.generate (file:///home/runner/work/doc-vite/doc-vite/node_modules/rollup/dist/es/shared/node-entry.js:17361:13)
    at async file:///home/runner/work/doc-vite/doc-vite/node_modules/rollup/dist/es/shared/node-entry.js:25619:27
    at async catchUnfinishedHookActions (file:///home/runner/work/doc-vite/doc-vite/node_modules/rollup/dist/es/shared/node-entry.js:24706:20)
```
暂不确定该问题由何引起。如果你知道解决办法，欢迎提出。

**Comment by hanzn-zzx** [comment]
我在试这个究竟是那一段引起的问题。
好像分批次的复制不会有问题吧

**Comment by hanzn-zzx** [comment]
报错在**2.4问题解决**那一段，我来试试重写

**Comment by hanzn-zzx** [comment]
解决了，你那个2.4第一条的超链接**samlukeyes**没有链接导致报错。
但就奇怪，为啥vuepress同样没有却没报错，vitepress就报错了
